import type { SubscriptionTemplate } from '~/store/subscriptionStore'

export const ALL_TEMPLATES: SubscriptionTemplate[] = [
  // ── Streaming ──────────────────────────────────────────────────────────────
  {
    label: 'Netflix',
    name: 'Netflix',
    domain: 'https://netflix.com',
    billingCycle: 'monthly',
    price: 15.99,
    currency: 'USD',
    category: 'Streaming',
    popular: true,
  },
  {
    label: 'Disney+',
    name: 'Disney+',
    domain: 'https://disneyplus.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Streaming',
    popular: true,
  },
  {
    label: 'Amazon Prime',
    name: 'Amazon Prime Video',
    domain: 'https://amazon.com',
    billingCycle: 'monthly',
    price: 8.99,
    currency: 'USD',
    category: 'Streaming',
    popular: true,
  },
  {
    label: 'YouTube Premium',
    name: 'YouTube Premium',
    domain: 'https://youtube.com',
    billingCycle: 'monthly',
    price: 13.99,
    currency: 'USD',
    category: 'Streaming',
    popular: true,
  },
  {
    label: 'Apple TV+',
    name: 'Apple TV+',
    domain: 'https://tv.apple.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'HBO Max',
    name: 'HBO Max',
    domain: 'https://max.com',
    billingCycle: 'monthly',
    price: 15.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'Hulu',
    name: 'Hulu',
    domain: 'https://hulu.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'Paramount+',
    name: 'Paramount+',
    domain: 'https://paramountplus.com',
    billingCycle: 'monthly',
    price: 5.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'Peacock',
    name: 'Peacock',
    domain: 'https://peacocktv.com',
    billingCycle: 'monthly',
    price: 5.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'Crunchyroll',
    name: 'Crunchyroll',
    domain: 'https://crunchyroll.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Streaming',
  },
  {
    label: 'MUBI',
    name: 'MUBI',
    domain: 'https://mubi.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Streaming',
  },

  // ── Music ──────────────────────────────────────────────────────────────────
  {
    label: 'Spotify',
    name: 'Spotify',
    domain: 'https://spotify.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Music',
    popular: true,
  },
  {
    label: 'Apple Music',
    name: 'Apple Music',
    domain: 'https://music.apple.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Music',
    popular: true,
  },
  {
    label: 'YouTube Music',
    name: 'YouTube Music',
    domain: 'https://music.youtube.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Music',
  },
  {
    label: 'Tidal',
    name: 'Tidal',
    domain: 'https://tidal.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Music',
  },
  {
    label: 'Amazon Music',
    name: 'Amazon Music Unlimited',
    domain: 'https://music.amazon.com',
    billingCycle: 'monthly',
    price: 8.99,
    currency: 'USD',
    category: 'Music',
  },
  {
    label: 'Deezer',
    name: 'Deezer',
    domain: 'https://deezer.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Music',
  },
  {
    label: 'Qobuz',
    name: 'Qobuz Studio',
    domain: 'https://qobuz.com',
    billingCycle: 'monthly',
    price: 12.99,
    currency: 'USD',
    category: 'Music',
  },

  // ── Cloud ──────────────────────────────────────────────────────────────────
  {
    label: 'Google One',
    name: 'Google One',
    domain: 'https://one.google.com',
    billingCycle: 'monthly',
    price: 2.99,
    currency: 'USD',
    category: 'Cloud',
    popular: true,
  },
  {
    label: 'iCloud+',
    name: 'iCloud+',
    domain: 'https://apple.com/icloud',
    billingCycle: 'monthly',
    price: 2.99,
    currency: 'USD',
    category: 'Cloud',
    popular: true,
  },
  {
    label: 'Dropbox',
    name: 'Dropbox Plus',
    domain: 'https://dropbox.com',
    billingCycle: 'monthly',
    price: 11.99,
    currency: 'USD',
    category: 'Cloud',
  },
  {
    label: 'OneDrive',
    name: 'Microsoft OneDrive',
    domain: 'https://onedrive.live.com',
    billingCycle: 'monthly',
    price: 1.99,
    currency: 'USD',
    category: 'Cloud',
  },
  {
    label: 'Box',
    name: 'Box Personal',
    domain: 'https://box.com',
    billingCycle: 'monthly',
    price: 10,
    currency: 'USD',
    category: 'Cloud',
  },
  {
    label: 'pCloud',
    name: 'pCloud Premium',
    domain: 'https://pcloud.com',
    billingCycle: 'monthly',
    price: 4.99,
    currency: 'USD',
    category: 'Cloud',
  },

  // ── AI Tools ───────────────────────────────────────────────────────────────
  {
    label: 'ChatGPT Plus',
    name: 'ChatGPT Plus',
    domain: 'https://chatgpt.com',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'AI Tools',
    popular: true,
  },
  {
    label: 'Claude Pro',
    name: 'Claude Pro',
    domain: 'https://claude.ai',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'AI Tools',
    popular: true,
  },
  {
    label: 'Cursor',
    name: 'Cursor Pro',
    domain: 'https://cursor.com',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'AI Tools',
    popular: true,
  },
  {
    label: 'Midjourney',
    name: 'Midjourney',
    domain: 'https://midjourney.com',
    billingCycle: 'monthly',
    price: 10,
    currency: 'USD',
    category: 'AI Tools',
    popular: true,
  },
  {
    label: 'Perplexity Pro',
    name: 'Perplexity Pro',
    domain: 'https://perplexity.ai',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'AI Tools',
  },
  {
    label: 'Gemini Advanced',
    name: 'Gemini Advanced',
    domain: 'https://gemini.google.com',
    billingCycle: 'monthly',
    price: 19.99,
    currency: 'USD',
    category: 'AI Tools',
  },
  {
    label: 'Copilot Pro',
    name: 'Microsoft Copilot Pro',
    domain: 'https://microsoft.com/copilot',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'AI Tools',
  },
  {
    label: 'Grok',
    name: 'Grok Premium',
    domain: 'https://x.ai',
    billingCycle: 'monthly',
    price: 16,
    currency: 'USD',
    category: 'AI Tools',
  },

  // ── Developer Tools ────────────────────────────────────────────────────────
  {
    label: 'GitHub Copilot',
    name: 'GitHub Copilot',
    domain: 'https://github.com',
    billingCycle: 'monthly',
    price: 10,
    currency: 'USD',
    category: 'Developer Tools',
    popular: true,
  },
  {
    label: 'GitLab',
    name: 'GitLab Premium',
    domain: 'https://gitlab.com',
    billingCycle: 'monthly',
    price: 19,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'JetBrains',
    name: 'JetBrains All Products',
    domain: 'https://jetbrains.com',
    billingCycle: 'monthly',
    price: 24.9,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Linear',
    name: 'Linear',
    domain: 'https://linear.app',
    billingCycle: 'monthly',
    price: 8,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Vercel Pro',
    name: 'Vercel Pro',
    domain: 'https://vercel.com',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Sentry',
    name: 'Sentry Team',
    domain: 'https://sentry.io',
    billingCycle: 'monthly',
    price: 26,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Postman',
    name: 'Postman Basic',
    domain: 'https://postman.com',
    billingCycle: 'monthly',
    price: 14,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Datadog',
    name: 'Datadog Pro',
    domain: 'https://datadoghq.com',
    billingCycle: 'monthly',
    price: 15,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Netlify',
    name: 'Netlify Pro',
    domain: 'https://netlify.com',
    billingCycle: 'monthly',
    price: 19,
    currency: 'USD',
    category: 'Developer Tools',
  },
  {
    label: 'Cloudflare',
    name: 'Cloudflare Pro',
    domain: 'https://cloudflare.com',
    billingCycle: 'monthly',
    price: 20,
    currency: 'USD',
    category: 'Developer Tools',
  },

  // ── Productivity ───────────────────────────────────────────────────────────
  {
    label: 'Notion',
    name: 'Notion Plus',
    domain: 'https://notion.so',
    billingCycle: 'monthly',
    price: 16,
    currency: 'USD',
    category: 'Productivity',
    popular: true,
  },
  {
    label: 'Adobe CC',
    name: 'Adobe Creative Cloud',
    domain: 'https://adobe.com',
    billingCycle: 'monthly',
    price: 54.99,
    currency: 'USD',
    category: 'Productivity',
    popular: true,
  },
  {
    label: 'Microsoft 365',
    name: 'Microsoft 365',
    domain: 'https://microsoft.com',
    billingCycle: 'monthly',
    price: 6.99,
    currency: 'USD',
    category: 'Productivity',
    popular: true,
  },
  {
    label: 'Figma',
    name: 'Figma Professional',
    domain: 'https://figma.com',
    billingCycle: 'monthly',
    price: 12,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: 'Canva Pro',
    name: 'Canva Pro',
    domain: 'https://canva.com',
    billingCycle: 'monthly',
    price: 12.99,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: 'Slack',
    name: 'Slack Pro',
    domain: 'https://slack.com',
    billingCycle: 'monthly',
    price: 7.25,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: '1Password',
    name: '1Password',
    domain: 'https://1password.com',
    billingCycle: 'monthly',
    price: 2.99,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: 'Obsidian Sync',
    name: 'Obsidian Sync',
    domain: 'https://obsidian.md',
    billingCycle: 'monthly',
    price: 8,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: 'Todoist',
    name: 'Todoist Pro',
    domain: 'https://todoist.com',
    billingCycle: 'monthly',
    price: 4,
    currency: 'USD',
    category: 'Productivity',
  },
  {
    label: 'Readwise',
    name: 'Readwise',
    domain: 'https://readwise.io',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Productivity',
  },

  // ── Gaming ─────────────────────────────────────────────────────────────────
  {
    label: 'Xbox Game Pass',
    name: 'Xbox Game Pass Ultimate',
    domain: 'https://xbox.com',
    billingCycle: 'monthly',
    price: 14.99,
    currency: 'USD',
    category: 'Gaming',
    popular: true,
  },
  {
    label: 'PlayStation Plus',
    name: 'PlayStation Plus Essential',
    domain: 'https://playstation.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Gaming',
    popular: true,
  },
  {
    label: 'Nintendo Online',
    name: 'Nintendo Switch Online',
    domain: 'https://nintendo.com',
    billingCycle: 'monthly',
    price: 3.99,
    currency: 'USD',
    category: 'Gaming',
  },
  {
    label: 'EA Play',
    name: 'EA Play',
    domain: 'https://ea.com/ea-play',
    billingCycle: 'monthly',
    price: 4.99,
    currency: 'USD',
    category: 'Gaming',
  },
  {
    label: 'Apple Arcade',
    name: 'Apple Arcade',
    domain: 'https://apple.com/apple-arcade',
    billingCycle: 'monthly',
    price: 6.99,
    currency: 'USD',
    category: 'Gaming',
  },
  {
    label: 'GeForce NOW',
    name: 'GeForce NOW Priority',
    domain: 'https://nvidia.com/geforce-now',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Gaming',
  },

  // ── Health & Fitness ───────────────────────────────────────────────────────
  {
    label: 'Strava',
    name: 'Strava',
    domain: 'https://strava.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Health & Fitness',
  },
  {
    label: 'Calm',
    name: 'Calm',
    domain: 'https://calm.com',
    billingCycle: 'monthly',
    price: 14.99,
    currency: 'USD',
    category: 'Health & Fitness',
  },
  {
    label: 'Headspace',
    name: 'Headspace',
    domain: 'https://headspace.com',
    billingCycle: 'monthly',
    price: 12.99,
    currency: 'USD',
    category: 'Health & Fitness',
  },
  {
    label: 'Whoop',
    name: 'Whoop',
    domain: 'https://whoop.com',
    billingCycle: 'monthly',
    price: 30,
    currency: 'USD',
    category: 'Health & Fitness',
  },
  {
    label: 'Peloton',
    name: 'Peloton App',
    domain: 'https://onepeloton.com',
    billingCycle: 'monthly',
    price: 12.99,
    currency: 'USD',
    category: 'Health & Fitness',
  },
  {
    label: 'Fitbod',
    name: 'Fitbod',
    domain: 'https://fitbod.me',
    billingCycle: 'monthly',
    price: 12.99,
    currency: 'USD',
    category: 'Health & Fitness',
  },

  // ── Education ──────────────────────────────────────────────────────────────
  {
    label: 'Duolingo Plus',
    name: 'Duolingo Plus',
    domain: 'https://duolingo.com',
    billingCycle: 'monthly',
    price: 6.99,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'Coursera+',
    name: 'Coursera Plus',
    domain: 'https://coursera.org',
    billingCycle: 'monthly',
    price: 59,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'Skillshare',
    name: 'Skillshare',
    domain: 'https://skillshare.com',
    billingCycle: 'monthly',
    price: 13.99,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'Brilliant',
    name: 'Brilliant',
    domain: 'https://brilliant.org',
    billingCycle: 'monthly',
    price: 24.99,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'LinkedIn Learning',
    name: 'LinkedIn Learning',
    domain: 'https://linkedin.com/learning',
    billingCycle: 'monthly',
    price: 39.99,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'MasterClass',
    name: 'MasterClass',
    domain: 'https://masterclass.com',
    billingCycle: 'monthly',
    price: 15,
    currency: 'USD',
    category: 'Education',
  },
  {
    label: 'Udemy',
    name: 'Udemy Personal Plan',
    domain: 'https://udemy.com',
    billingCycle: 'monthly',
    price: 19.99,
    currency: 'USD',
    category: 'Education',
  },

  // ── News & Media ───────────────────────────────────────────────────────────
  {
    label: 'NYT',
    name: 'New York Times',
    domain: 'https://nytimes.com',
    billingCycle: 'monthly',
    price: 17,
    currency: 'USD',
    category: 'News & Media',
  },
  {
    label: 'The Athletic',
    name: 'The Athletic',
    domain: 'https://theathletic.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'News & Media',
  },
  {
    label: 'Medium',
    name: 'Medium',
    domain: 'https://medium.com',
    billingCycle: 'monthly',
    price: 5,
    currency: 'USD',
    category: 'News & Media',
  },
  {
    label: 'The Economist',
    name: 'The Economist',
    domain: 'https://economist.com',
    billingCycle: 'monthly',
    price: 22,
    currency: 'USD',
    category: 'News & Media',
  },
  {
    label: 'Washington Post',
    name: 'Washington Post',
    domain: 'https://washingtonpost.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'News & Media',
  },
  {
    label: 'The Information',
    name: 'The Information',
    domain: 'https://theinformation.com',
    billingCycle: 'monthly',
    price: 42,
    currency: 'USD',
    category: 'News & Media',
  },

  // ── Finance ────────────────────────────────────────────────────────────────
  {
    label: 'YNAB',
    name: 'YNAB',
    domain: 'https://youneedabudget.com',
    billingCycle: 'monthly',
    price: 14.99,
    currency: 'USD',
    category: 'Finance',
  },
  {
    label: 'TradingView',
    name: 'TradingView Pro',
    domain: 'https://tradingview.com',
    billingCycle: 'monthly',
    price: 14.95,
    currency: 'USD',
    category: 'Finance',
  },
  {
    label: 'Monarch Money',
    name: 'Monarch Money',
    domain: 'https://monarchmoney.com',
    billingCycle: 'monthly',
    price: 14.99,
    currency: 'USD',
    category: 'Finance',
  },
  {
    label: 'Copilot Money',
    name: 'Copilot Money',
    domain: 'https://copilot.money',
    billingCycle: 'monthly',
    price: 13,
    currency: 'USD',
    category: 'Finance',
  },
  {
    label: 'Quicken',
    name: 'Quicken Deluxe',
    domain: 'https://quicken.com',
    billingCycle: 'monthly',
    price: 5.99,
    currency: 'USD',
    category: 'Finance',
  },

  // ── 🇬🇧 United Kingdom ─────────────────────────────────────────────────────
  {
    label: 'BritBox',
    name: 'BritBox',
    domain: 'https://britbox.com',
    billingCycle: 'monthly',
    price: 5.99,
    currency: 'GBP',
    category: 'Streaming',
    region: 'UK',
  },
  {
    label: 'NOW TV',
    name: 'NOW TV Entertainment',
    domain: 'https://nowtv.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'GBP',
    category: 'Streaming',
    region: 'UK',
  },
  {
    label: 'Sky TV',
    name: 'Sky TV',
    domain: 'https://sky.com',
    billingCycle: 'monthly',
    price: 26,
    currency: 'GBP',
    category: 'Streaming',
    region: 'UK',
  },
  {
    label: 'ITVX Premium',
    name: 'ITVX Premium',
    domain: 'https://itv.com',
    billingCycle: 'monthly',
    price: 3.99,
    currency: 'GBP',
    category: 'Streaming',
    region: 'UK',
  },
  {
    label: 'DAZN UK',
    name: 'DAZN UK',
    domain: 'https://dazn.com',
    billingCycle: 'monthly',
    price: 19.99,
    currency: 'GBP',
    category: 'Streaming',
    region: 'UK',
  },
  {
    label: 'The Guardian',
    name: 'The Guardian',
    domain: 'https://theguardian.com',
    billingCycle: 'monthly',
    price: 11.99,
    currency: 'GBP',
    category: 'News & Media',
    region: 'UK',
  },
  {
    label: 'The Times',
    name: 'The Times',
    domain: 'https://thetimes.co.uk',
    billingCycle: 'monthly',
    price: 26,
    currency: 'GBP',
    category: 'News & Media',
    region: 'UK',
  },

  // ── 🇫🇷 France ─────────────────────────────────────────────────────────────
  {
    label: 'Canal+',
    name: 'Canal+',
    domain: 'https://canalplus.com',
    billingCycle: 'monthly',
    price: 25.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'France',
  },
  {
    label: 'OCS',
    name: 'OCS',
    domain: 'https://ocs.fr',
    billingCycle: 'monthly',
    price: 14.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'France',
  },
  {
    label: 'Molotov Plus',
    name: 'Molotov Plus',
    domain: 'https://molotov.tv',
    billingCycle: 'monthly',
    price: 3.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'France',
  },
  {
    label: 'Cafeyn',
    name: 'Cafeyn',
    domain: 'https://cafeyn.co',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'France',
  },
  {
    label: 'Le Monde',
    name: 'Le Monde',
    domain: 'https://lemonde.fr',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'France',
  },
  {
    label: "L'Équipe+",
    name: "L'Équipe+",
    domain: 'https://lequipe.fr',
    billingCycle: 'monthly',
    price: 6.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'France',
  },

  // ── 🇩🇪 Germany ────────────────────────────────────────────────────────────
  {
    label: 'RTL+',
    name: 'RTL+',
    domain: 'https://plus.rtl.de',
    billingCycle: 'monthly',
    price: 6.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Germany',
  },
  {
    label: 'Sky DE',
    name: 'Sky Deutschland',
    domain: 'https://sky.de',
    billingCycle: 'monthly',
    price: 25,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Germany',
  },
  {
    label: 'MagentaTV',
    name: 'MagentaTV',
    domain: 'https://telekom.de/magenta-tv',
    billingCycle: 'monthly',
    price: 10,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Germany',
  },
  {
    label: 'DAZN DE',
    name: 'DAZN Deutschland',
    domain: 'https://dazn.com',
    billingCycle: 'monthly',
    price: 29.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Germany',
  },
  {
    label: 'Bild+',
    name: 'Bild+',
    domain: 'https://bild.de',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'Germany',
  },
  {
    label: 'Kicker+',
    name: 'Kicker+',
    domain: 'https://kicker.de',
    billingCycle: 'monthly',
    price: 4.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'Germany',
  },

  // ── 🇪🇸 Spain ──────────────────────────────────────────────────────────────
  {
    label: 'Movistar+',
    name: 'Movistar+',
    domain: 'https://movistar.es',
    billingCycle: 'monthly',
    price: 14,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Spain',
  },
  {
    label: 'Atresplayer',
    name: 'Atresplayer Premium',
    domain: 'https://atresplayer.com',
    billingCycle: 'monthly',
    price: 4.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Spain',
  },
  {
    label: 'El País',
    name: 'El País Digital',
    domain: 'https://elpais.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'Spain',
  },

  // ── 🇮🇹 Italy ──────────────────────────────────────────────────────────────
  {
    label: 'Mediaset Infinity',
    name: 'Mediaset Infinity+',
    domain: 'https://mediasetinfinity.mediaset.it',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Italy',
  },
  {
    label: 'DAZN IT',
    name: 'DAZN Italia',
    domain: 'https://dazn.com',
    billingCycle: 'monthly',
    price: 34.99,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Italy',
  },
  {
    label: 'Sky IT',
    name: 'Sky Italia',
    domain: 'https://sky.it',
    billingCycle: 'monthly',
    price: 19.9,
    currency: 'EUR',
    category: 'Streaming',
    region: 'Italy',
  },
  {
    label: 'Corriere della Sera',
    name: 'Corriere della Sera',
    domain: 'https://corriere.it',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'EUR',
    category: 'News & Media',
    region: 'Italy',
  },

  // ── 🇯🇵 Japan ──────────────────────────────────────────────────────────────
  {
    label: 'U-NEXT',
    name: 'U-NEXT',
    domain: 'https://unext.jp',
    billingCycle: 'monthly',
    price: 2189,
    currency: 'JPY',
    category: 'Streaming',
    region: 'Japan',
  },
  {
    label: 'ABEMA Premium',
    name: 'ABEMA Premium',
    domain: 'https://abema.tv',
    billingCycle: 'monthly',
    price: 960,
    currency: 'JPY',
    category: 'Streaming',
    region: 'Japan',
  },
  {
    label: 'd Anime Store',
    name: 'd Anime Store',
    domain: 'https://animestore.docomo.ne.jp',
    billingCycle: 'monthly',
    price: 440,
    currency: 'JPY',
    category: 'Streaming',
    region: 'Japan',
  },
  {
    label: 'Niconico',
    name: 'Niconico Premium',
    domain: 'https://nicovideo.jp',
    billingCycle: 'monthly',
    price: 550,
    currency: 'JPY',
    category: 'Streaming',
    region: 'Japan',
  },
  {
    label: 'Hulu JP',
    name: 'Hulu Japan',
    domain: 'https://happyon.jp',
    billingCycle: 'monthly',
    price: 1026,
    currency: 'JPY',
    category: 'Streaming',
    region: 'Japan',
  },
  {
    label: 'LINE MUSIC',
    name: 'LINE MUSIC',
    domain: 'https://music.line.me',
    billingCycle: 'monthly',
    price: 980,
    currency: 'JPY',
    category: 'Music',
    region: 'Japan',
  },
  {
    label: 'AWA',
    name: 'AWA',
    domain: 'https://awa.fm',
    billingCycle: 'monthly',
    price: 980,
    currency: 'JPY',
    category: 'Music',
    region: 'Japan',
  },
  {
    label: 'Nikkei Digital',
    name: 'Nikkei Digital',
    domain: 'https://nikkei.com',
    billingCycle: 'monthly',
    price: 4277,
    currency: 'JPY',
    category: 'News & Media',
    region: 'Japan',
  },

  // ── 🇰🇷 South Korea ────────────────────────────────────────────────────────
  {
    label: 'Wavve',
    name: 'Wavve',
    domain: 'https://wavve.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Streaming',
    region: 'South Korea',
  },
  {
    label: 'TVING',
    name: 'TVING',
    domain: 'https://tving.com',
    billingCycle: 'monthly',
    price: 10.99,
    currency: 'USD',
    category: 'Streaming',
    region: 'South Korea',
  },
  {
    label: 'Watcha',
    name: 'Watcha',
    domain: 'https://watcha.com',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'USD',
    category: 'Streaming',
    region: 'South Korea',
  },
  {
    label: 'Melon',
    name: 'Melon',
    domain: 'https://melon.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Music',
    region: 'South Korea',
  },
  {
    label: 'Genie Music',
    name: 'Genie Music',
    domain: 'https://genie.co.kr',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Music',
    region: 'South Korea',
  },
  {
    label: 'FLO',
    name: 'FLO',
    domain: 'https://music-flo.com',
    billingCycle: 'monthly',
    price: 7.99,
    currency: 'USD',
    category: 'Music',
    region: 'South Korea',
  },
  {
    label: 'Naver Plus',
    name: 'Naver Plus Membership',
    domain: 'https://naver.com',
    billingCycle: 'monthly',
    price: 4.99,
    currency: 'USD',
    category: 'Productivity',
    region: 'South Korea',
  },

  // ── 🇦🇺 Australia ──────────────────────────────────────────────────────────
  {
    label: 'Stan',
    name: 'Stan',
    domain: 'https://stan.com.au',
    billingCycle: 'monthly',
    price: 16,
    currency: 'AUD',
    category: 'Streaming',
    region: 'Australia',
  },
  {
    label: 'Binge',
    name: 'Binge',
    domain: 'https://binge.com.au',
    billingCycle: 'monthly',
    price: 10,
    currency: 'AUD',
    category: 'Streaming',
    region: 'Australia',
  },
  {
    label: 'Kayo Sports',
    name: 'Kayo Sports',
    domain: 'https://kayosports.com.au',
    billingCycle: 'monthly',
    price: 25,
    currency: 'AUD',
    category: 'Streaming',
    region: 'Australia',
  },
  {
    label: 'Foxtel Now',
    name: 'Foxtel Now',
    domain: 'https://foxtel.com.au',
    billingCycle: 'monthly',
    price: 25,
    currency: 'AUD',
    category: 'Streaming',
    region: 'Australia',
  },
  {
    label: 'The Australian',
    name: 'The Australian',
    domain: 'https://theaustralian.com.au',
    billingCycle: 'monthly',
    price: 28,
    currency: 'AUD',
    category: 'News & Media',
    region: 'Australia',
  },

  // ── 🇨🇦 Canada ─────────────────────────────────────────────────────────────
  {
    label: 'Crave',
    name: 'Crave',
    domain: 'https://crave.ca',
    billingCycle: 'monthly',
    price: 19.99,
    currency: 'CAD',
    category: 'Streaming',
    region: 'Canada',
  },
  {
    label: 'TSN Direct',
    name: 'TSN Direct',
    domain: 'https://tsn.ca',
    billingCycle: 'monthly',
    price: 19.99,
    currency: 'CAD',
    category: 'Streaming',
    region: 'Canada',
  },
  {
    label: 'Sportsnet+',
    name: 'Sportsnet+',
    domain: 'https://sportsnet.ca',
    billingCycle: 'monthly',
    price: 9.99,
    currency: 'CAD',
    category: 'Streaming',
    region: 'Canada',
  },
  {
    label: 'Club illico',
    name: 'Club illico',
    domain: 'https://clubillico.com',
    billingCycle: 'monthly',
    price: 11.99,
    currency: 'CAD',
    category: 'Streaming',
    region: 'Canada',
  },

  // ── 🇮🇳 India ──────────────────────────────────────────────────────────────
  {
    label: 'Hotstar',
    name: 'Disney+ Hotstar',
    domain: 'https://hotstar.com',
    billingCycle: 'monthly',
    price: 299,
    currency: 'INR',
    category: 'Streaming',
    region: 'India',
  },
  {
    label: 'Sony LIV',
    name: 'Sony LIV',
    domain: 'https://sonyliv.com',
    billingCycle: 'monthly',
    price: 299,
    currency: 'INR',
    category: 'Streaming',
    region: 'India',
  },
  {
    label: 'Zee5',
    name: 'Zee5',
    domain: 'https://zee5.com',
    billingCycle: 'monthly',
    price: 149,
    currency: 'INR',
    category: 'Streaming',
    region: 'India',
  },
  {
    label: 'JioCinema',
    name: 'JioCinema Premium',
    domain: 'https://jiocinema.com',
    billingCycle: 'monthly',
    price: 29,
    currency: 'INR',
    category: 'Streaming',
    region: 'India',
  },
  {
    label: 'Gaana+',
    name: 'Gaana+',
    domain: 'https://gaana.com',
    billingCycle: 'monthly',
    price: 149,
    currency: 'INR',
    category: 'Music',
    region: 'India',
  },
  {
    label: 'JioSaavn Pro',
    name: 'JioSaavn Pro',
    domain: 'https://jiosaavn.com',
    billingCycle: 'monthly',
    price: 99,
    currency: 'INR',
    category: 'Music',
    region: 'India',
  },

  // ── 🇨🇳 China ──────────────────────────────────────────────────────────────
  {
    label: 'iQIYI',
    name: 'iQIYI',
    domain: 'https://iqiyi.com',
    billingCycle: 'monthly',
    price: 25,
    currency: 'CNY',
    category: 'Streaming',
    region: 'China',
  },
  {
    label: 'Youku',
    name: 'Youku',
    domain: 'https://youku.com',
    billingCycle: 'monthly',
    price: 25,
    currency: 'CNY',
    category: 'Streaming',
    region: 'China',
  },
  {
    label: 'Bilibili',
    name: 'Bilibili Premium',
    domain: 'https://bilibili.com',
    billingCycle: 'monthly',
    price: 25,
    currency: 'CNY',
    category: 'Streaming',
    region: 'China',
  },
  {
    label: 'NetEase Music',
    name: 'NetEase Cloud Music',
    domain: 'https://music.163.com',
    billingCycle: 'monthly',
    price: 15,
    currency: 'CNY',
    category: 'Music',
    region: 'China',
  },
  {
    label: 'QQ Music',
    name: 'QQ Music',
    domain: 'https://y.qq.com',
    billingCycle: 'monthly',
    price: 15,
    currency: 'CNY',
    category: 'Music',
    region: 'China',
  },

  // ── 🇧🇷 Brazil ─────────────────────────────────────────────────────────────
  {
    label: 'Globoplay',
    name: 'Globoplay',
    domain: 'https://globoplay.globo.com',
    billingCycle: 'monthly',
    price: 22,
    currency: 'USD',
    category: 'Streaming',
    region: 'Brazil',
  },
  {
    label: 'Paramount+ BR',
    name: 'Paramount+ Brasil',
    domain: 'https://paramountplus.com.br',
    billingCycle: 'monthly',
    price: 18,
    currency: 'USD',
    category: 'Streaming',
    region: 'Brazil',
  },
  {
    label: 'Claro Video',
    name: 'Claro Video',
    domain: 'https://clarovideo.com',
    billingCycle: 'monthly',
    price: 15,
    currency: 'USD',
    category: 'Streaming',
    region: 'Brazil',
  },

  // ── 🇸🇬 Singapore ──────────────────────────────────────────────────────────
  {
    label: 'Viu',
    name: 'Viu Premium',
    domain: 'https://viu.com',
    billingCycle: 'monthly',
    price: 9.98,
    currency: 'SGD',
    category: 'Streaming',
    region: 'Singapore',
  },
  {
    label: 'Singtel TV GO',
    name: 'Singtel TV GO',
    domain: 'https://singtel.com',
    billingCycle: 'monthly',
    price: 11.99,
    currency: 'SGD',
    category: 'Streaming',
    region: 'Singapore',
  },
]

/** The templates marked as globally popular — shown in the "Popular" tab by default. */
export const POPULAR_TEMPLATES = ALL_TEMPLATES.filter((t) => t.popular).slice(0, 5)

/** The unique country regions present in the template list, in insertion order. */
export const TEMPLATE_REGIONS = Array.from(new Set(ALL_TEMPLATES.map((t) => t.region).filter(Boolean))) as string[]

/** Flag emoji lookup for region names. */
export const REGION_FLAGS: Record<string, string> = {
  UK: '🇬🇧',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Spain: '🇪🇸',
  Italy: '🇮🇹',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  Canada: '🇨🇦',
  India: '🇮🇳',
  China: '🇨🇳',
  Brazil: '🇧🇷',
  Singapore: '🇸🇬',
}
